### ISSUE TITLE
what does the census transform

### ISSUE THREAD

**Issue by shaldor0315** [ppliuboy/DDFlow#1]
hi,i have read the paper,but i also don't understand the census transform !what does the census mean?

**Comment by ppliuboy** [comment]
Census transform is a non-parametric local transform proposed in [Nonparametric Local Transforms for Computing Visual Correspondence](https://www2.cs.duke.edu/courses/spring06/cps296.1/handouts/Zabih%20Woodfill%201994.pdf). After census transform, we can measure the similarity of images using Hamming distance. Census transform is robust for illumination changes and optical flow estimation. Please check the following paper "[Why is the Census Transform Good for Robust Optic Flow Computation?](https://www.mia.uni-saarland.de/Publications/hafner-ssvm13.pdf)" for detail.
