### ISSUE TITLE
How to generate the binary occlusion map in the paper？

### ISSUE THREAD

**Issue by guyibai** [ppliuboy/DDFlow#16]
I got  yellow images after setting _mode=generate_fake_flow_occlusion_.

**Comment by ppliuboy** [comment]
https://github.com/ppliuboy/DDFlow/blob/master/utils.py#L83

**Comment by guyibai** [comment]
This is not my trouble. I want to know how to convert _occ_fw_ and _occ_bw_ into the binary images as in the paper.

**Comment by ppliuboy** [comment]
The output is already a binary image, with only 0 and 1. You can dirrectly save it.
