### ISSUE TITLE
why it can work in extract_config.py: import configparser

### ISSUE THREAD

**Issue by ANABUR920** [ppliuboy/DDFlow#2]
In fact, in Python 2.7,  there is not import configparser, but import ConfigParser. And if you fix it to ConfigParser, it turns out to another trouble. So I wonder to know why it can run in configparser. :)

**Comment by ppliuboy** [comment]
We implement it with anaconda, and it indeed has package configparser even for python 2.7, that's why it works.

**Comment by ANABUR920** [comment]
thank you so much, your work is so inspired and thanks for your reply
