### ISSUE TITLE
About number of parameters/model size

### ISSUE THREAD

**Issue by RuiFeiHe** [ppliuboy/DDFlow#4]
Hello, I'm calculating the number of parameters of your ddflow model, and I'm pretty shocked at the results. 
According to to my calculations, your model have 4,273,628 parameters, but PWCNet has around 8.75M parameters. I'm confused about the huge difference since you have pretty close model architecture. 
Can you help me out?
Thank you!

**Comment by ppliuboy** [comment]
Yes, we have similar architecture, but the implementation details may have something difference. If you want to find the reason, please check the implementation details of both.
