### ISSUE TITLE
The training procedure of KITTI 2015 dataset

### ISSUE THREAD

**Issue by wanghao14** [ppliuboy/DDFlow#5]
Hi, Pengpeng. You have chosen KITTI 2015 dataset as an example to interpret the training procedure, and I want to make sure whether it should restore the checkpoint pretrained on FlyingChairs.

**Comment by ppliuboy** [comment]
Yes, as written in the paper, we restore the unsupervised pre-trained model on FlyingChairs.

**Comment by wanghao14** [comment]
Thanks for your reply.
