### ISSUE TITLE
关于无监督训练遇到的问题

### ISSUE THREAD

**Issue by redcping** [ppliuboy/DDFlow#6]
hi,感谢放出源码，DDFlow和SelFlow都是非常nice的工作。
我用DDFLow训练自己的数据时出现以下问题，具体描述如下：
实验：预训练模型kitti/data_distillation，数据是自己的数据左右图（数据由多个不同参数相机拍摄），现象：按照Step 1: Training without data distillation训练，发现越来越差
疑问：在新 的数据集上无监督训练该注意什么？或者说步骤不一样了？

期待收到你的解答，祝生活愉快！

**Comment by ppliuboy** [comment]
Hi, 仅从你的描述我很难解答。新的数据无监督学习，步骤是一样的，讲两点注意事项吧。首先，要确保输入的训练pair有很强相关性，比如属于同一个video或者同一场景不同view，因为如果训练的pair两张图片完全不相关，会导致无法收敛，这样求光流也没有意义。第二，训练时如果从头开始train，要follow step 1，首先不考虑occlusion训练一段时间，然后再把occlusion考虑进去训练，或者以一个pre-train的model作为initialization。
