### ISSUE TITLE
Unstable training

### ISSUE THREAD

**Issue by JohnnieXDU** [ppliuboy/DDFlow#7]
Hi, the backbone of DDFlow  and SelFlow are both PWC-Net. I am trying to train the PWC-Net on FlyingChairs from scratch. 

However, I found that training PWC-net with losses from level 2, 3, 4, 5 and 6 is unstable, and hard to convergence. Instead, training with the only loss from level 2 is much more stable and easier to convergence. 

So, do you meet the same problem while you training the PWC-net? Besides, how many days will take for training the PWC-net? It seems will take almost 1 week for Flying Chairs....

Thanks!

**Comment by ppliuboy** [comment]
Hi,

As writen in our paper, I only compute the loss for the last level (bilinear upsampling for level 2), you shall also find it in our code.

For the training time, I use 4 gpus with batch size 4. It convergents very quickly.

**Comment by JohnnieXDU** [comment]
Thank you! So the real batch size should be 4*4?


| |
yjiao_xdu
|
|
邮箱：yjiao_xdu@163.com
|

Signature is customized by Netease Mail Master

On 01/08/2020 23:41, Pengpeng Liu wrote:

Hi,

As writen in our paper, I only compute the loss for the last level (bilinear upsampling for level 2), you shall also find it in our code.

For the training time, I use 4 gpus with batch size 4. It convergents very quickly.

**Comment by ppliuboy** [comment]
No, batch size is 4
