### ISSUE TITLE
Value for $\alpha_{2}$ in the occlusion estimation

### ISSUE THREAD

**Issue by gcilli** [ppliuboy/DDFlow#8]
Dear authors, 
according to the paper (Section: "Occlusion Estimation"), the value for $\alpha_{2}$ is 0.05. However, in the code, it is set to 0.5. Is there something I am missing or it is indeed a typo?

Here the link to the lines I'm referring to:

https://github.com/ppliuboy/DDFlow/blob/0d47420a9496f825e512b6590e5acf205207ee01/utils.py#L93
https://github.com/ppliuboy/DDFlow/blob/0d47420a9496f825e512b6590e5acf205207ee01/utils.py#L94

Thank you.

**Comment by ppliuboy** [comment]
We use 0.5 in our experiments.
